apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-dev-gh
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/svenkatrav0408/ArgoCD-config.git
    targetRevision: HEAD
    path: ArgoCD-config/dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true