apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-stage-gh
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/svenkatrav0408/ArgoCD-config.git
    path: stage
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true