apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-stage-gh
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/your-repo.git
    path: ArgoCD-config/stage
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true