apiVersion: apps/v1
kind: Deployment
metadata:
  name: seven-eleven-myapp-dev
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: svenkatrav0408/demo-app:node-1.0
        ports:
        - containerPort: 8080
