apiVersion: apps/v1
kind: Deployment
metadata:
  name: seven-eleven-myapp-stage
  namespace: stage
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: svenkatrav0408/argocd:latest
        ports:
        - containerPort: 8080