apiVersion: v1
kind: Service
metadata:
  name: myapp-service-stage
  namespace: stage
spec:
  selector:
    app: myapp
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000    # Changed to match container port