apiVersion: apps/v1
kind: Deployment
metadata:
  name: seven-eleven-myapp-qa
  namespace: qa
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: svenkatrav0408/argocd:latest-amd64
        env:
        - name: NODE_ENV
          value: "qa"
        ports:
        - containerPort: 3000   # Changed to match the application port
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10